name: Build

on: [push, repository_dispatch]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        haxe-version: [3.4.7, 4.0.5, 4.1.5, 4.2.2]
        target: [html5]
        # target: [html5, linux, windows, mac]
        exclude:
          - os: windows-latest
            haxe-version: 3.4.7
          - os: ubuntu-latest
            target: windows
          - os: ubuntu-latest
            target: mac
          - os: windows-latest
            target: linux
          - os: windows-latest
            target: mac
          - os: macos-latest
            target: linux
          - os: macos-latest
            target: windows


    steps:
    - uses: actions/checkout@v1
    - name: Setup Haxe (${{ matrix.target }}, haxe ${{ matrix.haxe-version }}, ${{ matrix.os }})
      uses: krdlab/setup-haxe@v1
      with:
        haxe-version: ${{ matrix.haxe-version }}

    - name: Cache haxelib
      id: cache-haxelib
      uses: actions/cache@v3.0.11
      with:
        path: .haxelib/
        key: ${{ matrix.os }}-${{ hashFiles('.github/workflows/project/install.hxml') }}

    - name: Setup haxelibs (${{ matrix.target }}, haxe ${{ matrix.haxe-version }}, ${{ matrix.os }})
      if: steps.cache-haxelib.outputs.cache-hit != 'true'
      run: |
        haxelib newrepo
        haxelib install --always --quiet .github/workflows/project/install.hxml
        echo "y" | haxelib run openfl setup

    - name: Setup haxeui (${{ matrix.target }}, haxe ${{ matrix.haxe-version }}, ${{ matrix.os }})
      run: |
        git clone --branch master https://github.com/haxeui/haxeui-core.git --depth=1
        haxelib dev haxeui-core haxeui-core
        haxelib dev haxeui-openfl .

    - name: Build app (${{ matrix.target }}, haxe ${{ matrix.haxe-version }}, ${{ matrix.os }})
      run: |
        cd .github/workflows/project
        haxelib run openfl build ${{ matrix.target }}
